export default [
  {
    period: "April 2017 - Jan 2017",
    role: "HRIS Analayst > Support",
    contract: "Regular",
    with: "Mercer Eveber (Workday Partner)",
    domain: "HCM & Absence",
    countries: "UK, Japan, France, USA",
    for: "Luxury (Chanel)",
  },
  {
    period: "Nov 2017 - Jan 2018",
    role: "HRIS Analayst > Project",
    contract: "Regular",
    with: "Mercer Eveber (Workday Partner)",
    domain: "Absence & Time Tracking",
    countries: "France, Spain",
    for: "IT (Agap2)",
  },
  {
    period: "Feb 2018 - Aug 2018",
    role: "HRIS Lead / Implementer",
    contract: "Regular",
    with: "Mercer Eveber (Workday Partner)",
    domain: "Absence & Time Tracking",
    countries: "France, Germany",
    for: "Dating Application (Match, Meetic)",
  },
  {
    period: "July 2018 - Nov 2018",
    role: "HRIS Lead / Implementer",
    contract: "Regular",
    with: "Mercer Eveber (Workday Partner)",
    domain: "Absence & Time Tracking",
    countries: "22 countries (mostly Europe)",
    for: "Travel Agency (Club Med)",
  },
  {
    period: "Oct 2018 - Nov 2018",
    role: "HRIS Analyst > Support",
    contract: "Regular",
    with: "Mercer Eveber (Workday Partner)",
    domain: "HCM + Absence & Time Tracking",
    countries: "Europe + USA",
    for: "4 clients: Insurance, Online shopping, Retailer, Luxury",
  },
  {
    period: "Dec 2018 - May 2019",
    role: "HRIS Lead / Implementer",
    contract: "Regular",
    with: "Mercer Eveber (Workday Partner)",
    domain: "Absence & Time Tracking",
    countries: "Europe + USA",
    for: "Loudspeaker manufacturer (L-Acoustics)",
  },
  {
    period: "March 2019 - Aug 2019",
    role: "Staffing Manager",
    contract: "Regular",
    with: "Mercer Eveber (Workday Partner)",
    domain: "Staffing Management",
    countries: "Europe",
    for: "Mercer Everbe",
  },
  {
    period: "Sept 2019 - April 2020",
    role: "HRIS Specialist: Audit, Improvement, Support",
    contract: "Fixed Term",
    with: "Activision Blizzard King (Client)",
    domain: "Absence",
    countries: "Spain, UK, USA, Germany, Sweden, FRA, IR",
    for: "Video Games (Activision Blizzard King)",
  },
  {
    period: "May 2020 - Jan 2021",
    role: "HRIS Lead / Implementer",
    contract: "Fixed Term",
    with: "Activision Blizzard King (Client)",
    domain: "Absence & Time Tracking",
    countries: "France, Ireland",
    for: "Video Games (Activision Blizzard King)",
  },
  {
    period: "Feb 2021 - July 2021",
    role: "HRIS Lead / Implementer",
    contract: "Contractor",
    with: "Activision Blizzard King (Client)",
    domain: "Absence & Time Tracking",
    countries: "Canada",
    for: "Video Game Studio (Beenox)",
  },
  {
    period: "July 2021 - Oct 2021",
    role: "HRIS Lead / Implementer & Support",
    contract: "Contractor",
    with: "Activision (25%) & PWC(50%)",
    domain: "Absence & Time Tracking",
    countries: "Benelux + Europe",
    for: "2 clients: Transporter & Video Games",
  },
  {
    period: "Oct 2021 - Feb 2022",
    role: "HRIS Implementer",
    contract: "Contractor",
    with: "PWC",
    domain: "Absence & Time Tracking",
    countries: "Benelux",
    for: "Transporter (H.Essers)",
  },
  {
    period: "Feb 2022 - Aug 2022",
    role: "HRIS Lead & Implementer",
    contract: "Contractor",
    with: "Klarna",
    domain: "Absence & Time Tracking",
    countries: "Europe + North America",
    for: "Klarna",
  },
  {
    period: "Aug 2022 - Today",
    role: "HRIS Lead & Implementer",
    contract: "Contractor",
    with: "HR Path",
    domain: "Absence & Time Tracking BAU and Projects",
    countries: "France",
    for: "HR Path",
  },
];
